Test
weicheng2138/vue3-input pull request #2
Opened 2022-08-31 03:42 UTC by Cindy6166

2022-09-14 09:04 UTC, Cindy6166 commented
@weicheng2138 i fixed the warning issue by including the required props in the test.

2022-09-15 13:36 UTC, weicheng2138 requested changes
Please change the highlighted part of the code

2022-09-15 13:36 UTC, weicheng2138 commented on src/components/BasicInput.spec.ts
> +    const wrapper = mount(BasicInput)
@Cindy6166 
1. As a default situation for BasicInput, it should have two props which is placeholder and modelValue.
2. If you see some warning over the console, remember to resolve it (it should not show anything even `console.log`). Because it tells you there are something that is missing. For example, the warning is telling you are mssing props when you are mounting the component.
![擷取](https://user-images.githubusercontent.com/13548635/188584993-02129593-229a-4929-9469-415d5f0c4f78.PNG)

2022-09-15 13:36 UTC, weicheng2138 commented on src/components/BasicInput.spec.ts
> +    const wrapper = mount(BasicInput)
Also your IDE do notify you to fix the problem, Although I don't why the first default mount didn't show the bottom red line
![擷取](https://user-images.githubusercontent.com/13548635/188589308-4a6bfb89-8aa0-45e6-87ad-46d14350ca42.PNG)

2022-09-15 13:40 UTC, merged